---
title: "Exercises_W2"
author: "Brihatee Mattapullut"
date: 06/10/2026 # Automatically uses today's date
date-format: "DD/MM/YYYY"             # British/Australian date format

# Output Config
format: 
  # HTML Output
  html:
    theme: cosmo          # Modern Bootstrap theme with clean typography
    highlight-style: a11y # High-contrast syntax highlighting for code
    toc: true             # Includes a Table of Contents
    toc-depth: 3          # Captures down to sub-subsections (e.g., 3.1.1)
    toc-location: left    # Pins TOC to left sidebar so it doesn't block main page
    toc-title: "Contents" # Custom title for the TOC sidebar
    number-sections: true # Numbers sections automatically (e.g., 1, 1.1, 2)
    code-fold: true       # Collapses code blocks by default under a dropdown
    code-summary: "Show code" # Label text on collapsed code blocks
    code-tools: true      # Adds global code menu (Show/Hide All Code) at top right
    code-copy: true       # Adds a one-click copy button to code blocks
    embed-resources: true # Bundles images/CSS into a single stand-alone HTML file
    df-print: paged       # Formats data frames into interactive paged tables
    fig-height: 5         # Default plot height in inches
    fig-width: 8          # Default plot width in inches
    #fig-responsive: true # Scales figures smoothly across screen sizes
    smooth-scroll: true   # Enables smooth scrolling when clicking TOC links
---

# Loading libraries
```{r}
library(tidyverse)
library(readxl)
```


# 2.12 Keystone exercise: Estuary Fish Survey - Data Rescue Mission


## Importing the files
```{r}

#estuary catch log data
#the excel workbook has different tabs 
#need to be loaded individually
catch1 <- read_excel(here::here("data/estuary_catch_log.xlsx"), sheet = "Lower_ross")
catch2 <- read_excel("../data/estuary_catch_log.xlsx", sheet = 2)
catch3 <- read_excel("../data/estuary_catch_log.xlsx", sheet = 3)
catch4 <- read_excel("../data/estuary_catch_log.xlsx", sheet = 4)  

#estuary metadata file
estuary_metadata <- read.csv(here::here("data/estuary_metadata.csv")) 
  
#estuary sonde data file
estuary_sonde_data <- 
read.csv(here::here("data/estuary_sonde_data.csv")) 
  
#species dictionary file
species_dictionary <- 
read.csv(here::here("data/species_dictionary.csv"))
```


## Combining all the different tabs in the catch log excel 

```{r}

```

